### ISSUE TITLE
iptables port opening

### ISSUE THREAD

**Issue by fernandohonig** [rackspace-cookbooks/varnish#55]
This cookbook is not opening iptables port for varnish. It should open varnish frontend port.

**Comment by prometheanfire** [comment]
then we need a generic iptables library :P

**Comment by mattjbarlow** [comment]
@fernandohonig I think iptables should live in the downstream cookbook that calls libraries from this one. Otherwise, we make more assumptions about how people are using the cookbook and try to bolt on helpers. This adds dependencies. I checked a few similar cookbooks like [mysql](https://github.com/chef-cookbooks/mysql), [rabbitmq](https://github.com/jjasghar/rabbitmq), and [redisio](https://github.com/brianbianco/redisio) and didn't see iptables rules being configured. Let me know what you think.
