### ISSUE TITLE
varnish_install not able to call apt-get update

### ISSUE THREAD

**Issue by mmarschall** [rackspace-cookbooks/varnish#56]
My cookbook depends on the varnish cookbook and my recipe looks like this:

```
varnish_install "webapp" do
  vendor_repo true
end
```

Running chef-client produces the following error:
```
ERROR: resource apt_repository[varnish-cache] is configured to notify resource execute[apt-get update] with action nothing, but execute[apt-get update] cannot be found in the resource collection. apt_repository[varnish-cache] is defined in /var/chef/cache/cookbooks/varnish/libraries/varnish_install.rb:36:in `add_vendor_repo'
```

In the repo recipe the apt recipe gets included. I don't see a similar call in varnish_install.rb.

I need to add
```
include_recipe 'apt'
```

to my recipe before I call varnish_install to make it work.
That shouldn't be necessary.

**Comment by martinb3** [comment]
For my own notes: Due to `use_inline_resources`, I'm not sure even if we did add an include inside varnish_install.rb [here](https://github.com/rackspace-cookbooks/varnish/blob/master/libraries/varnish_install.rb#L43), that it would make the `execute[apt-get update]` resource available (it would depend on if the recipe had already been loaded elsewhere). This feels like a limitation of `use_inline_resources`.

**Comment by mattjbarlow** [comment]
I think it is okay to remove [this line](https://github.com/rackspace-cookbooks/varnish/blob/09d30c5bf382def59bffda05dc86752fc39b7782/libraries/varnish_install.rb#L42) which will prevent this error. It was copied over from the [repo.rb](https://github.com/rackspace-cookbooks/varnish/blob/09d30c5bf382def59bffda05dc86752fc39b7782/recipes/repo.rb) recipe. I'm not sure why it was added to begin with. @prometheanfire what are your thoughts?

**Comment by jhmartin** [comment]
Any update on this?
